# Generated by Django 3.0.3 on 2021-04-19 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim', '0012_item_service_jsonExtField'),
        ('core', '0011_auto_20210324_1528'),
        ('claim_ai_quality', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAiQualityMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_ai_mutations', to='claim.Claim')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='claims_ai_evaluation', to='core.MutationLog')),
            ],
            options={
                'db_table': 'claim_ai_quality_EvaluateByAIMutation',
                'managed': True,
            },
        ),
    ]
