# Generated by Django 3.0.14 on 2022-02-20 11:23

from django.db import migrations


def _create_claim_ai_user(apps, schema_editor):
    USERNAME = "_ClaimAIAdmin"
    from core.models import TechnicalUser
    from core.services import create_or_update_core_user
    from core.models import User
    if not User.objects.filter(username=USERNAME).exists():
        t_user, t_user_created = TechnicalUser.objects.get_or_create(
            **{"username": USERNAME, "is_staff": True, "is_superuser": True, }
        )
        create_or_update_core_user(user_uuid=None, username=USERNAME, t_user=t_user)


class Migration(migrations.Migration):
    dependencies = [
        ('claim_ai_quality', '0004_claimbundleevaluationresult_historicalclaimbundleevaluationresult'),
        ('core', '0015_missing_roles')
    ]

    operations = [
        migrations.RunPython(_create_claim_ai_user),
    ]
