# Generated by Django 3.0.14 on 2022-02-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0012_item_service_jsonExtField'),
        ('claim_ai_quality', '0005_claim_ai_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimbundleevaluationresult',
            name='claims',
            field=models.ManyToManyField(related_name='bundle_evaluations', to='claim.Claim'),
        ),
    ]
