# Generated by Django 3.0.14 on 2022-02-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0012_item_service_jsonExtField'),
        ('claim_ai_quality', '0006_auto_20220222_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimbundleevaluationresult',
            name='claims',
        ),
        migrations.CreateModel(
            name='BundleClaimEvaluationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claim_ai_quality.ClaimBundleEvaluationResult')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_evaluation', to='claim.Claim')),
            ],
        ),
    ]
